language: java
sudo: false
body='{
"request": {
  "branch":"sample",
  "message":"Triggering docker selion travis from SeLion"
}}'
curl -s -X POST -H "Content-Type: application/json" -H "Accept: application/json" -H "Travis-API-Version: 3" -H "Authorization: token 9Nt4p4g7rt36Z2CdU0Fbbg" -d "$body" https://api.travis-ci.org/repo/ysecaran%2Fdocker-selion/requests
jdk:
  - oraclejdk7
script:
  - sh -e utilities/run-travis-ci-tests.sh
addons:
  sauce_connect: true
notifications:
  irc:
    channels:
      - "irc.freenode.org#selion"
    on_success: always
    on_failure: always
    use_notice: true
  webhooks: 
    urls:
      - https://webhooks.gitter.im/e/a8fc34e427360ced7ebf
    on_success: change
    on_failure: always
    on_start: never
