language: java
sudo: false
jdk:
  - oraclejdk7
script:
  - sh -e utilities/run-travis-ci-tests.sh
after_success:
  - '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && sh -e utilities/trigger-another-travis-ci.sh
addons:
  sauce_connect: true
notifications:
  irc:
    channels:
      - "irc.freenode.org#selion"
    on_success: always
    on_failure: always
    use_notice: true
  webhooks: 
    urls:
      - https://webhooks.gitter.im/e/a8fc34e427360ced7ebf
    on_success: change
    on_failure: always
    on_start: never
